DROP DATABASE IF EXISTS HOTEL;
CREATE DATABASE IF NOT EXISTS HOTEL;
USE HOTEL;

CREATE TABLE IF NOT EXISTS HUESPED  (
    CI VARCHAR(50) PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    MAIL VARCHAR(100) NOT NULL UNIQUE,
    TELEFONO VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY,
    TIPO VARCHAR(30) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL
    CHECK (PRECIO > 0)
);

CREATE TABLE IF NOT EXISTS HABITACION (
    ID_HABITACION INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO INT NOT NULL UNIQUE,
    ESTADO VARCHAR(50) NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    CONSTRAINT FK_HABITACION_CATEGORIA
        FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE IF NOT EXISTS RESERVA (
    ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    ID_HABITACION INT NOT NULL,
    CI_HUESPED VARCHAR(50) NOT NULL,
    FECHAINICIO DATE NOT NULL,
    FECHAFIN DATE NOT NULL,
    FECHARESERVA DATE NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    CONSTRAINT FK_RESERVA_HABITACION
        FOREIGN KEY (ID_HABITACION)
        REFERENCES HABITACION(ID_HABITACION),
    CONSTRAINT FK_RESERVA_HUESPED
        FOREIGN KEY (CI_HUESPED)
        REFERENCES HUESPED(CI),
    CONSTRAINT CHK_RESERVA_FECHAS
        CHECK (FECHAINICIO < FECHAFIN)
);

CREATE TABLE IF NOT EXISTS ESTADIA (
    ID_ESTADIA INT AUTO_INCREMENT PRIMARY KEY,
    ID_RESERVA INT NOT NULL,
    FECHA_INICIO_ESTADIA DATE NOT NULL,
    FECHA_FIN_ESTADIA DATE,
    CONSTRAINT FK_ESTADIA_RESERVA
        FOREIGN KEY (ID_RESERVA)
        REFERENCES RESERVA(ID_RESERVA),
    CONSTRAINT CHK_ESTADIA_FECHAS
        CHECK (
            FECHA_FIN_ESTADIA IS NULL
            OR FECHA_INICIO_ESTADIA < FECHA_FIN_ESTADIA
        )
);


CREATE TABLE IF NOT EXISTS CONSUMO_ADICIONAL (
    ID_CONSUMO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ESTADIA INT NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    FECHA DATE NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_CONSUMO_ESTADIA
        FOREIGN KEY (ID_ESTADIA)
        REFERENCES ESTADIA(ID_ESTADIA),
    CONSTRAINT CHK_CONSUMO_MONTO
        CHECK (MONTO > 0)
);

CREATE TABLE IF NOT EXISTS PAGO  (
    ID_PAGO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    MEDIO_DE_PAGO VARCHAR(50) NOT NULL,
    CI_HUESPED VARCHAR(50) NOT NULL,
    CONSTRAINT FK_PAGO_HUESPED
        FOREIGN KEY (CI_HUESPED)
        REFERENCES HUESPED(CI),
    CONSTRAINT CHK_PAGO_MONTO
        CHECK (MONTO > 0)
);

CREATE TABLE if not exists TOTAL_HUESPED  (
    CI_HUESPED VARCHAR(50) PRIMARY KEY,
    TOTAL_ADEUDADO DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_TOTAL_HUESPED
        FOREIGN KEY (CI_HUESPED)
        REFERENCES HUESPED(CI)
);


CREATE TABLE if not exists AUDITORIA  (
    ID_AUDITORIA INT AUTO_INCREMENT PRIMARY KEY,
    ID_HABITACION INT NOT NULL,
    FECHA DATETIME NOT NULL,
    USUARIO_BD VARCHAR(100),
    MOTIVO VARCHAR(255) NOT NULL,
    CONSTRAINT FK_AUDITORIA_HABITACION
        FOREIGN KEY (ID_HABITACION)
        REFERENCES HABITACION(ID_HABITACION)
) ENGINE=MyISAM;
